name: WolfyUtilities
version: '${version}'
main: com.wolfyscript.utilities.spigot.WolfyCoreSpigotBootstrap
api-version: 1.16
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "org.apache.commons:commons-lang3:3.12.0"
  - "${libs.com.google.inject.guice.get()}"
  - "${libs.org.reflections.reflections.get()}"
  - "${libs.it.unimi.dsi.fastutil.get()}"
  - "${libs.com.typesafe.config.get()}"
  - "${libs.com.fasterxml.jackson.core.jackson.annotations.get()}"
  - "${libs.com.fasterxml.jackson.core.jackson.core.get()}"
  - "${libs.com.fasterxml.jackson.core.jackson.databind.get()}"
  - "${libs.net.kyori.adventure.api.get()}"
  - "${libs.net.kyori.adventure.text.minimessage.get()}"
  - "${libs.net.kyori.adventure.platform.bukkit.get()}"
  - "${libs.org.jetbrains.kotlin.stdlib.get()}"

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - PlaceholderAPI
  - eco
  - zAuctionHouseV3
  - SCore

permissions:
  wolfyutilities.command.query_debug:
    default: op
    description: "Command to debug NBT querries on the item in the hand"